### ISSUE TITLE
extract.cmd - Erreur réseau

### ISSUE THREAD

**Issue by bourriquetFR** [VEAF/VEAF-mission-converter#16]
Bonjour,

Lorsque j'effectue un extract, une erreur "réseau" apparaît.

warning package.json: No license field
warning Mission-Contrebande@1.0.0: No license field
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
**error An unexpected error occurred: "https://registry.yarnpkg.com/veaf-mission-creation-tools: connect ETIMEDOUT 212.27.38.252:443".
info If you think this is a bug, please open a bug report with the information provided in "C:\\VEAF\\Mission-Contrebande\\yarn-error.log".**
info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.
extracting MIZ files

Ci-dessous, le fichier de log en question.

[yarn-error.log](https://github.com/VEAF/VEAF-mission-converter/files/12936810/yarn-error.log)

(je me demande s'il n'y a pas un update à faire suite au changement d'hébergeur récent)

**Comment by davidp57** [comment]
Salut Bourriquet, ce type d'erreur n'est pas lié au changement d'hébergeur, ça n'a pas de lien avec nos repo Github. J'ai analysé le fichier de log, je ne vois rien qui pourrait remettre en cause nos outils VEAF.

Peut-être une erreur réseau momentanée chez toi ?

Dans l'immédiat, je clôture le ticket car je ne peux rien apporter
